[project]
name = "papagei-foundation-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "peakutils>=1.3.5",
    "pyarrow>=20.0.0",
    "statsmodels>=0.14.5",
    "tabpfn>=2.0.9",
    "torch-ecg>=0.0.31",
]
